
key_pare = {
#pragma mark - track => ACCRepoTrackModel
"recordRouteNumber": "repoTrack",
"referString" : "repoTrack",
"selectedMethod" : "repoTrack",
"enterFrom" : "repoTrack",
"enterMethod" : "repoTrack",
"enterEditPageMethod" : "repoTrack",
"enterShootPageExtra" : "repoTrack",
"hasWatermark" : "repoTrack",
"hasEndWatermark" : "repoTrack",
"storyShootEntrance" : "repoTrack",
"storyGuidePlusIconType" : "repoTrack",
"friendLabel" : "repoTrack",
#pragma mark - draft =>  ACCRepoDraftModel
"originalDraft" : "repoDraft",
"originalModel" : "repoDraft",
"taskID" : "repoDraft",
"draftPath" : "repoDraft",
"isBackUp" : "repoDraft",
"isDraft" : "repoDraft",
"draftTempProduct" : "repoDraft",
"editFrequency" : "repoDraft",
#pragma mark - basic info => ACCRepoContextModel
"createVersion" : "repoContext",
"uuid" : "repoContext",
"createId" : "repoContext",
"videoSource" : "repoContext",
"videoType" : "repoContext",
"videoRecordType" : "repoContext",
"isLive" : "repoContext",
"isMVVideo" : "repoContext",
"feedType" : "repoContext",
"maxDuration" : "repoContext",
"videoLenthMode" : "repoContext",
"recordSourceFrom" : "repoContext",
"photoToVideoPhotoCountType" : "repoContext",
"isQuickStoryPictureVideoType" : "repoContext",
"activityVideoType" : "repoContext",
#pragma mark - video info => ACCRepoVideoInfoModel
"video" : "repoVideoInfo",
"videoMuted" : "repoVideoInfo",
"sizeOfVideo" : "repoVideoInfo",
"isExposureOptmize" : "repoVideoInfo",
"capturedPhotoWithWatermark" : "repoVideoInfo",
"cameraFrameRatio" : "repoVideoInfo",
"videoFrameRatio" : "repoVideoInfo",
"fps" : "repoVideoInfo",
"isFastImportVideo" : "repoVideoInfo",
"enableHDRNet" : "repoVideoInfo",
"needExpandVideoSize" : "repoVideoInfo",
"canvasType" : "repoVideoInfo",

#pragma mark - publish config info => ACCRepoPublishConfigModel
"publishTitle" : "repoPublishConfig",
"titleExtraInfo" : "repoPublishConfig",
"isHashTag" : "repoPublishConfig",
"dynamicCoverStartTime" : "repoPublishConfig",
"recommendedAICoverIndex" : "repoPublishConfig",
"recommendedAICoverTime" : "repoPublishConfig",
"coverTitleSelectedFrom" : "repoPublishConfig",
"coverTitleSelectedId" : "repoPublishConfig",
"coverImage" : "repoPublishConfig",
"firstFrameImage" : "repoPublishConfig",
"tosCoverURI" : "repoPublishConfig",
"coverTextModel" : "repoPublishConfig",
"coverTextImage" : "repoPublishConfig",
"activityHashtagID" : "repoPublishConfig",
"isFirstPost" : "repoPublishConfig",
"hotSpotWord" : "repoPublishConfig",
"saveToAlbum" : "repoPublishConfig",

#pragma mark - sticker => ACCRepoStickerModel
"interactionStickers" : "repoSticker",
"dateTextStickerContent" : "repoSticker",
"interactionModel" : "repoSticker",
"imageText" : "repoSticker",
"imageTextFonts" : "repoSticker",
"imageTextFontEffectIds" : "repoSticker",
"textImage" : "repoSticker",
"pollImage" : "repoSticker",
"infoStickerArray" : "repoSticker",
"hasTextAdded" : "repoSticker",
"textReadingAssets" : "repoSticker",
"textReadingRanges" : "repoSticker",
"currentLyricStickerID" : "repoSticker",
"stickerID" : "repoSticker",
"gestureInvalidFrameValue" : "repoSticker",
#pragma mark - reshoot => ACCRepoReshootModel
"isReshoot" : "repoReshoot",
"fromCreateId" : "repoReshoot",
"fromTaskId" : "repoReshoot",
"recordVideoClipRange" : "repoReshoot",
"durationBeforeReshoot" : "repoReshoot",
"durationAfterReshoot" : "repoReshoot",
"fullRangeFragmentInfo" : "repoReshoot",
#pragma mark - voice changer => ACCRepoVoiceChangerModel
"voiceChangerID" : "repoVoiceChanger",
"voiceChangerChallengeID" : "repoVoiceChanger",
"voiceChangerChallengeName" : "repoVoiceChanger",
"voiceEffectSegments" : "repoVoiceChanger",
#pragma mark - cut same => ACCRepoCutSameModel
"cutSameEditedTexts" : "repoCutSame",
"accTemplateType" : "repoCutSame",
"templateModel" : "repoCutSame",
"cutSameMusicID" : "repoCutSame",
#pragma mark - Duet => ACCRepoDuetModel
"isDuet" : "repoDuet",
"duetSource" : "repoDuet",
"duetLocalSourceURL" : "repoDuet",
"furthestStep" : "repoDuet",
"duetLayout" : "repoDuet",
"duetOrCommentChainlength" : "repoDuet",
#pragma mark MV => ACCRepoMVModel
"mvModel" : "repoMV",
"mvMusic" : "repoMV",
"mvTemplateType" : "repoMV",
"templateModelId" : "repoMV",
"templateModelTip" : "repoMV",
"templateMaxMaterial" : "repoMV",
"templateMinMaterial" : "repoMV",
"templateMusicId" : "repoMV",
"templateMusicFileName" : "repoMV",
"templateMaterials" : "repoMV",
"mvChallengeName" : "repoMV",
"enableOriginSoundInMV" : "repoMV",
"mvID" : "repoMV",
"serverExecutedImageDict" : "repoMV",
"slideshowMVID" : "repoMV",

#pragma mark - Challenge => ACCRepoChallengeModel
"challenge" : "repoChallenge",
#pragma mark - Upload => ACCRepoUploadInfomationModel
"extraDict" : "repoUploadInfo",
"isSpeedChange" : "repoUploadInfo",
"exportTime" : "repoUploadInfo",
"videoClipMode" : "repoUploadInfo",
"originUploadVideoClipCount" : "repoUploadInfo",
"originUploadPhotoCount" : "repoUploadInfo",
"clipSourceType" : "repoUploadInfo",
"isMultiVideoUpload" : "repoUploadInfo",
"mediaSubType" : "repoUploadInfo",
"isFaceuVideoFirst" : "repoUploadInfo",
"toBeUploadedImage" : "repoUploadInfo",
"selectedUploadAssets" : "repoUploadInfo",
"sourceInfos" : "repoUploadInfo",
#pragma mark - Game => ACCRepoGameModel
"gameType" : "repoGame",
"game2DScore" : "repoGame",
#pragma mark - Filter => ACCRepoFilterModel
"capturedWithLightningFilter" : "repoFilter",
"editedWithLightningFilter" : "repoFilter",
"colorFilterId" : "repoFilter",
"colorFilterIntensityRatio" : "repoFilter",
#pragma mark - Caption => ACCRepoCaptionModel
"captionInfo" : "repoCaption",
"mixAudioUrl" : "repoCaption",
"mixAudioInfoMd5" : "repoCaption",
#pragma mark - Prop => ACCRepoPropModel
"propSelectedFrom" : "repoProp",
"totalStickerSavePhotos" : "repoProp",
"stickerBindedChallengeInPublishStepArray" : "repoProp",
"localPropId" : "repoProp",
"propBindMusicIDArray" : "repoProp",
#pragma mark - Edit Prop => ACCRepoEditPropModel
"displayTimeRanges" : "repoEditEffect",
#pragma mark - Music => ACCRepoMusicModel
"music" : "repoMusic",
"musicTrackModel" : "repoMusic",
"audioRange" : "repoMusic",
"voiceVolume" : "repoMusic",
"musicVolume" : "repoMusic",
"musicSelectFrom" : "repoMusic",
"musicUsageConfirmation" : "repoMusic",
"zipURI" : "repoMusic",
"isLVAudioFrameModel" : "repoMusic",
"bgmAsset" : "repoMusic",
"bgmClipRange" : "repoMusic",
"useSuggestClipRange" : "repoMusic",
"musicEditedFrom" : "repoMusic",
"musicSelectedFrom" : "repoMusic",
#pragma mark - Share => ACCRepoShareModel
"syncToToutiao" : "repoShare",
"syncToDuoshan" : "repoShare",
"shareVideoURL" : "repoShare",
"thirdAppKey" : "repoShare",
"shareModel" : "repoShare",
#pragma mark - Moment => ACCRepoMomentModel
"momentID" : "repoMoment",
"momentIdentity" : "repoMoment",
"momentOriginVoiceVolume" : "repoMoment",
#pragma mark - Flow Control => ACCRepoFlowControlModel
"step" : "repoFlowControl",
"disableBackToTabBar" : "repoFlowControl",
"hasRecoveredAudioFragments" : "repoFlowControl",
"videoRecordButtonType" : "repoFlowControl",
#pragma mark - record info => ACCRecordInformationRepoModel
"fragmentInfo" : "repoRecordInfo",
#pragma mark - text mode => ACCRepoTextModeModel
"isTextMode" : "repoTextMode",
"textModel" : "repoTextMode",
#pragma mark - QuickStory => ACCRepoQuickStoryModel
"isQuickStory" : "repoQuickStory",
"isQuickShootTarget" : "repoQuickStory",
"editPageButtonStyle" : "repoQuickStory",
"isAvatarQuickStory" : "repoQuickStory",
"videoCode": "repoQuickStory",
"saveStoryToLocal" : "repoQuickStory",
"shootWay" : "repoQuickStory",

}

function_keypare= {
    "sourceInfosArray": "repoUploadInfo",
    "isAIVideoClipMode": "repoUploadInfo",

    "isClassicalMV": "repoCutSame",

    "draftFolder": "repoDraft",
    "tagForDraftFromBackEdit": "repoDraft",

    "customStickersInfos": "repoSticker",
    "supportNewEditClip": "repoContext",
    "newClipForMultiUploadVideos": "repoContext",

    "hadUseBeauty": "repoBeauty",

    "recommendedAICoverTrackInfo": "repoPublishConfig",
    "recommendedAICoverTrackInfoWithCoverStartTime": "repoPublishConfig",
    "composedCoverImage": "repoPublishConfig",

    "beautifyTrackInfoDic": "repoRecordInfo",
    "shouldForbidCommerce": "repoRecordInfo",
    "originalFrameNamesArray": "repoRecordInfo",

    "audioDidChanged": "repoCaption",
    "resetAudioChangeFlag": "repoCaption",
    "feedbackCaptionWithAwemeId": "repoCaption",
    "queryCaptionsWithUrl": "repoCaption",

    "commonTrackInfoDic": "repoTrack",
    "performanceTrackInfoDic": "repoTrack",
    "referExtra": "repoTrack",
    "videoFragmentInfoDictionary": "repoTrack",
    "mediaCountInfo": "repoTrack",
    "getLogInfo": "repoTrack",
    "trackPostEvent": "repoTrack",

    "socialStickerTrackInfoDic": "repoSticker",
    "textStickerTrackInfo": "repoSticker",
    "supportMusicLyricSticker": "repoSticker",
    "infoStickerChallengeNames": "repoSticker",
    "infoStickerChallengeIDs": "repoSticker",
    "removeTextReadingInCurrentVideo": "repoSticker",
    "allAudioAssetsInVideoData": "repoSticker",
    "audioAssetInVideoDataWithKey": "repoSticker",
    "customStickersInfos": "repoSticker",

    "hasEditMusicRange": "repoMusic",
    "musicAsset": "repoMusic",

    "allAudioAssetsInVideoData": "repoSticker",
    "audioAssetInVideoDataWithKey": "repoSticker",
    "removeTextReadingInCurrentVideo": "repoSticker",
    "isMultiVideoFastImport": "repoVideoInfo",
    "isAIVideoClipMode": "repoUploadInfo",

    "stickerBindedChallengeArray": "repoProp",

    "hasVideoClipEdits": "repoReshoot",
    "getStickerSavePhotoCount": "repoReshoot",
    "removeVideoClipEdits": "repoReshoot",

    "allChallengeIdArray": "repoChallenge",
    "allChallengeNameArray": "repoChallenge",

    "currentBindChallengeNames": "repoChallengeBind",
    "currentBindChallengeIds": "repoChallengeBind",
    "markNeedRemoveWhenReRecord": "repoChallengeBind",

    "getLogInfo": "repoTrack",
    "mediaCountInfo": "repoTrack",
    "referExtra": "repoTrack",

    "specializedCanvasPhotoExportSettings": "repoVideoInfo",
    "isMultiVideoFastImport": "repoVideoInfo",
    "isVideoNeedReverse": "repoVideoInfo",

    "removeVideoClipEdits" : "repoReshoot",

    "isTC21RedPackageActivity" : "repoContext",
    "shouldSelectMusicAutomatically": "repoContext",
    "shouldUseMVMusic": "repoContext",

    "isOldDuet": "repoDuet",
    "challengeNames": "repoDuet",
    "challengeIDs": "repoDuet",

    "isFixedDuration": "repoFlowControl",

    "shouldEditWithLightningFilter": "repoQuickStory",
    "shouldBuildQuickStoryPanel": "repoQuickStory",
    "shouldDisableQuickPublishActionSheet": "repoQuickStory",

    "startTraceTimeForKey": "repoRecorderTrackerTool",
    "stopTraceTimeForKey": "repoRecorderTrackerTool",
    "addTrackTime": "repoRecorderTrackerTool",
    "trackerDic": "repoRecorderTrackerTool",
    "cleanTraceTime": "repoRecorderTrackerTool",

    "voiceEffectType": "repoVoiceChanger",
    "clearVoiceEffect": "repoVoiceChanger",
    "voiceEffectIDs": "repoVoiceChanger",

}

repo_keypare = {
    "repoTrack" : "ACCRepoTrackModel",
    "repoDraft": "ACCRepoDraftModel",
    "repoContext": "ACCRepoContextModel",
    "repoVideoInfo": "ACCRepoVideoInfoModel",
    "repoPublishConfig": "ACCRepoPublishConfigModel",
    "repoSticker": "AWEVideoPublishViewModel+RepoSticker",
    "repoReshoot": "ACCRepoReshootModel",
    "repoVoiceChanger": "ACCRepoVoiceChangerModel",
    "repoCutSame": "ACCRepoCutSameModel",
    "repoDuet": "ACCRepoDuetModel",
    "repoMV": "ACCRepoMVModel",
    "repoChallenge": "ACCRepoChallengeModel",
    "repoUploadInfo": "ACCRepoUploadInfomationModel",
    "repoGame": "ACCRepoGameModel",
    "repoFilter": "ACCRepoFilterModel",
    "repoCaption": "ACCRepoCaptionModel",
    "repoProp": "ACCRepoPropModel",
    "repoEditProp": "ACCRepoEditPropModel",
    "repoMusic": "ACCRepoMusicModel",
    "repoShare": "ACCRepoShareModel",
    "repoMoment": "ACCRepoMomentModel",
    "repoFlowControl": "ACCRepoFlowControlModel",
    "repoRecordInfo": "ACCRecordInformationRepoModel",
    "repoTextMode": "ACCRepoTextModeModel",
    "repoQuickStory": "ACCRepoQuickStoryModel",
    "repoEditEffect": "ACCRepoEditEffectModel",
}

replace_kaypare = {
    "AWEVideoPublishViewModel *publishModel" : "id<ACCRepositoryModules> repository",
    ":(AWEVideoPublishViewModel *)publishViewModel": ":(id<ACCRepositoryModules>)repository",
    "AWEVideoPublishViewModel *" : "id<ACCRepositoryModules>",
    "ACCEditViewControllerInputData *inputData": "id<ACCRepositoryModules> repository",
    "- (instancetype)initWithInputData:(ACCEditViewControllerInputData *)inputData" : "- (instancetype)initWithRepository:(id<ACCRepositoryModules>)repository",
    "_inputData = inputData" : "_repository = repository",
    "WithInputData:(ACCEditViewControllerInputData *)inputData": "WithRepository:(id<ACCRepositoryModules>)repository",
    '#import "ACCEditViewControllerInputData.h"\n': "",
    "WithInputData:self.inputData": "WithRepository:self.repository",
    "WithPublishModel": "WithRepository",
    "WithPublishViewModel": "WithRepository",
    "With:(AWEVideoPublishViewModel *)publishViewModel" : "With:(AWEVideoPublishViewModel *)publishViewModel",
    '#import "AWEVideoPublishViewModel.h"': '#import "ACCRepositoryModules.h"',
    '#import "AWEVideoPublishViewModel+Repository.h"': '#import "ACCRepositoryModules.h"',
}

startwith_keypare = {
    '#import "AWEVideoPublishViewModel+': '#import "ACCRepositoryModules.h"\n'
}

excludeFiles = ["PublishViewModel.m", "PublishViewModel.h", "PublishRepository"]